---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: wheezy-64
  driver_config:
    box: wheezy64
    box_url: http://debbuild.bigpoint.net/wheezy64.box
    customize:
      memory: 768
- name: jessie-64
  driver_config:
    box: jessie64
    box_url: http://debbuild.bigpoint.net/jessie64.box
    customize:
      memory: 768

suites:
  - name: percona
    run_list:
      - role[percona-server]
      - recipe[bp-percona::testdb]
    attributes:
      bp-percona: 
       credidentials: 
         - "bp-percona"
         - "mysql"
         - "testserver"
