---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: debian-7.4
  driver_config:
    customize:
      memory: 768
- name: debian-8.0
  driver_config:
    box_url: https://downloads.sourceforge.net/project/vagrantboxjessie/debian80.box
    customize:
      memory: 768
- name: centos-65
  driver_config:
    box: centos65-amd64
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
    customize:
      memory: 768

suites:
  - name: percona
    run_list:
      - role[percona-server]
      - recipe[bp-percona::testdb]
    attributes:
      bp-percona: 
       credidentials: 
         - "bp-percona"
         - "mysql"
         - "testserver"
